# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if index .Values "open-match-core" "enabled" }}
# Include this namespace only when doing `helm template`.
# helm 2 use namespace to manage its release so `helm install` with this namespace will be broken.
{{- if index .Values "usingHelmTemplate" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
{{- end }}
---
# Create a universal service account for open-match-core services.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.kubernetes.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
automountServiceAccountToken: true
---
# Create a service account for open-match-test services.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-match-test-service
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
automountServiceAccountToken: true
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: om-service-role
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
rules:
# Define om-service-role to use om-core-podsecuritypolicy
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - om-core-podsecuritypolicy
  verbs:
  - use
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: om-test-role
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
rules:
# Define om-test-role to use om-core-podsecuritypolicy
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - om-core-podsecuritypolicy
  verbs:
  - use
# Grant om-test-role get & list permission for k8s endpoints and pods resources
# Required for e2e in-cluster testing.
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  verbs:
  - get
  - list
---
# This applies om-test-role to the open-match-test-service account under the release namespace. 
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: om-test-role-binding
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: open-match-test-service
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: om-test-role
  apiGroup: rbac.authorization.k8s.io
---
# This applies om-service-role to the open-match unprivileged service account under the release namespace. 
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: om-service-role-binding
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.kubernetes.serviceAccount }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: om-service-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: om-redis-role
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
rules:
# Define om-redis-role to use om-redis-podsecuritypolicy
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - om-redis-podsecuritypolicy
  verbs:
  - use
---
# This applies om-redis role to the om-redis privileged service account under the release namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: om-redis-role-binding
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.redis.serviceAccount.name }} # Redis service account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: om-redis-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
