# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
#                   Open Match Script for Google Cloud Build                   #
################################################################################

# To run this locally:
# cloud-build-local --config=cloudbuild.yaml --dryrun=false --substitutions=_OM_VERSION=DEV .
# To run this remotely:
# gcloud builds submit --config=cloudbuild.yaml --substitutions=_OM_VERSION=DEV .

# Requires gcloud to be installed to work. (https://cloud.google.com/sdk/)
# gcloud auth login
# gcloud components install cloud-build-local

# This YAML contains all the build steps for building Open Match.
# All PRs are verified against this script to prevent build breakages and regressions.

# Conventions
# Each build step is ID'ed with "Prefix: Description".
#   The prefix portion determines what kind of step it is and it's impact.
#   Docker Image: Read-Only, outputs a docker image.
#   Lint: Read-Only, verifies correctness and formatting of a file.
#   Build: Read-Write, outputs a build artifact. Ok to run in parallel if the artifact will not collide with another one.
#   Generate: Read-Write, outputs files within /workspace that are used in other build step. Do not run these in parallel.
#   Setup: Read-Write, similar to generate but steps that run before any other step.

# Some useful things to know about Cloud Build.
# The root of this repository is always stored in /workspace.
#    Any modifications that occur within /workspace are persisted between builds anything else is forgotten.
# If a build step has intermediate files that need to be persisted for a future step then use volumes.
#    An example of this is the go-vol which is where the pkg/ data for go mod is stored.
#    More information here: https://cloud.google.com/cloud-build/docs/build-config#build_steps
# 

# https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/go
steps:
# TODO: Re-enable the docker image targets once they become hermetic.

#- id: 'Docker Image: backendapi'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-backendapi:${_OM_VERSION}-${SHORT_SHA}', 'cmd/backendapi']
#  waitFor: ['-']

#- id: 'Docker Image: frontendapi'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-frontendapi:${_OM_VERSION}-${SHORT_SHA}', 'cmd/frontendapi']
#  waitFor: ['-']

#- id: 'Docker Image: mmforc'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-mmforc:${_OM_VERSION}-${SHORT_SHA}', 'cmd/mmforc']
#  waitFor: ['-']

#- id: 'Docker Image: mmlogicapi'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-mmlogicapi:${_OM_VERSION}-${SHORT_SHA}', 'cmd/mmlogicapi']
#  waitFor: ['-']

# TODO: This image does not build.
#- id: 'Docker Image: Evaluator Simple'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-evaluator-simple:${_OM_VERSION}-${SHORT_SHA}', 'examples/evaluators/golang/simple']
#  waitFor: ['-']

#- id: 'Docker Image: openmatch-mmf-cs-mmlogic-simple'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-mmf-cs-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}', 'examples/functions/csharp/simple']
#  waitFor: ['-']

#- id: 'Docker Image: openmatch-mmf-go-mmlogic-simple'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-mmf-go-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}', 'examples/functions/golang/manual-simple']
#  waitFor: ['-']

#- id: 'Docker Image: openmatch-mmf-php-mmlogic-simple'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-mmf-php-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}', 'examples/functions/php/mmlogic-simple']
#  waitFor: ['-']

#- id: 'Docker Image: openmatch-mmf-py3-mmlogic-simple'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-mmf-py3-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}', 'examples/functions/python3/mmlogic-simple']
#  waitFor: ['-']

#- id: 'Docker Image: backendclient'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-backendclient:${_OM_VERSION}-${SHORT_SHA}', 'examples/backendclient']
#  waitFor: ['-']

#- id: 'Docker Image: clientloadgen'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-clientloadgen:${_OM_VERSION}-${SHORT_SHA}', 'test/cmd/clientloadgen']
#  waitFor: ['-']

#- id: 'Docker Image: frontendclient'
#  name: gcr.io/cloud-builders/docker
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/openmatch-frontendclient:${_OM_VERSION}-${SHORT_SHA}', 'test/cmd/frontendclient']
#  waitFor: ['-']

# Cannot enable, produces lots of errors but can be useful.
#- id: 'Lint: YAML Files'
#  name: wpengine/yamllint
#  args: ['/workspace']
#  waitFor: ['-']

- id: 'Lint: Kubernetes Configs'
  name: garethr/kubeval
  args: ['install/yaml/01-redis.yaml', 'install/yaml/02-open-match.yaml']
  waitFor: ['-']

- id: 'Setup: go mod'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'init', 'github.com/GoogleCloudPlatform/open-match']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['-']

- id: 'Setup: Pull Dependencies'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'tidy']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: go mod']

- id: 'Setup: Fix k8s.io/api Dependency'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'edit', '-require', 'k8s.io/api@v0.0.0-20190111032252-67edc246be36']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Pull Dependencies']

- id: 'Setup: Vendor Dependencies'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'vendor']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Fix k8s.io/api Dependency']

- id: 'Lint: Formatting'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'fmt', './...']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Lint: Vetting'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'vet', './...']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Test: 10x with Race Detection and Coverage'
  name: golang
  env: ['GO111MODULE=on']
  args: ['go', 'test', './...', '-race', '-test.count', '10', '-cover']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: All Binaries'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', './...']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: cmd/backendapi/backendapi'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'cmd/backendapi/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: cmd/frontendapi/frontendapi'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'cmd/frontendapi/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: cmd/mmforc/mmforc'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'cmd/mmforc/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: cmd/mmlogicapi/mmlogicapi'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'cmd/mmlogicapi/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: examples/functions/golang/manual-simple'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'examples/functions/golang/manual-simple/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: examples/backendclient'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'examples/backendclient/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: test/cmd/clientloadgen'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'test/cmd/clientloadgen/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

- id: 'Build: test/cmd/frontendclient'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', '-a', '-installsuffix', 'cgo', '.']
  dir: 'test/cmd/frontendclient/'
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: Vendor Dependencies']

artifacts:
    objects:
        location: gs://open-match-build-artifacts/output/
        paths:
            - cmd/backendapi/backendapi
            - cmd/frontendapi/frontendapi
            - cmd/mmforc/mmforc
            - cmd/mmlogicapi/mmlogicapi
            - examples/functions/golang/manual-simple/manual-simple
            - examples/backendclient/backendclient
            - test/cmd/clientloadgen/clientloadgen
            - test/cmd/frontendclient/frontendclient
# TODO: Enable when the Dockerfiles are hermetic.
images:
#- 'gcr.io/$PROJECT_ID/openmatch-backendapi:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-frontendapi:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-mmforc:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-mmlogicapi:${_OM_VERSION}-${SHORT_SHA}'
# Does not build
#- 'gcr.io/$PROJECT_ID/openmatch-evaluator-simple:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-mmf-cs-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-mmf-go-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-mmf-php-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-mmf-py3-mmlogic-simple:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-backendclient:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-clientloadgen:${_OM_VERSION}-${SHORT_SHA}'
#- 'gcr.io/$PROJECT_ID/openmatch-frontendclient:${_OM_VERSION}-${SHORT_SHA}'
#substitutions:
#    _OM_VERSION: 0.4.0
logsBucket: 'gs://open-match-build-logs/'
options:
  sourceProvenanceHash: ['SHA256']
  machineType: 'N1_HIGHCPU_8'
# TODO: The build is slow because we don't vendor. go get takes a very long time.
# Also we are rebuilding a lot of code unnecessarily. This should improve once
# we have new hermetic and reproducible Dockerfiles.
timeout: 1200s
# TODO Build Steps
# api/protobuf-spec/*: Build Protocol Buffers (golang, python, php)
# config/matchmaker_config.yaml: Lint this file so it's verified as a valid YAML file.
# deployments/k8s: Verify with kubelint.
# examples/profiles/*.json: Verify valid JSON files.
#
# Consolidate many of these build steps via Makefile.
# Caching of dependencies is a serious problem. Cloud Build does not complete within 20 minutes!

