kind: Service
apiVersion: v1
metadata:
  name: om-redis-master
spec:
  selector:
    app: mm
    tier: storage
  ports:
  - protocol: TCP
    port: 6379
    targetPort: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: mm
      tier: storage
  replicas: 1
  template:
    metadata:
      labels:
        app: mm
        tier: storage
    spec:
      containers:
      - name: redis-master
        image: redis:4.0.11
        command:
        - '/bin/sh'
        - '-c'
        - '[ -z "$(REDIS_PASSWORD)" ] && redis-server || redis-server --requirepass "$(REDIS_PASSWORD)"'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: om-redis
              key: redis-password
              optional: true
        ports:
        - name: redis
          containerPort: 6379