---
# Source: open-match/templates/om-configmap.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: om-configmap
  namespace: open-match
  labels:
    app: open-match
    component: config
data:
  backendapi_config.yaml: |-
    api:
      backend:
        backoff: '[2 32] *2 ~0.33 <30'
    debug: true
    logging:
      format: json
      level: debug
      source: false
    redis:
      pool:
        idleTimeout: 60
        maxActive: 0
        maxIdle: 3
      queryArgs:
        count: 10000
      results:
        pageSize: 10000
    
  frontendapi_config.yaml: |-
    api:
      frontend:
        backoff: '[2 32] *2 ~0.33 <300'
    debug: true
    logging:
      format: json
      level: debug
      source: false
    redis:
      pool:
        idleTimeout: 60
        maxActive: 0
        maxIdle: 3
      queryArgs:
        count: 10000
      results:
        pageSize: 10000
    
  mmforc_config.yaml: |-
    debug: true
    defaultImages:
      evaluator:
        name: 'ihrankouski/openmatch-evaluator-simple'
        tag: 'dev'
      mmf:
        name: 'ihrankouski/openmatch-mmf-py3-mmlogic-simple'
        tag: 'dev'
    evalutor:
      interval: 10
    logging:
      format: json
      level: debug
      source: false
    redis:
      pool:
        idleTimeout: 60
        maxActive: 0
        maxIdle: 3
      queryArgs:
        count: 10000
      results:
        pageSize: 10000
    
  mmlogicapi_config.yaml: |-
    debug: true
    logging:
      format: json
      level: debug
      source: false
    redis:
      pool:
        idleTimeout: 60
        maxActive: 0
        maxIdle: 3
      queryArgs:
        count: 10000
      results:
        pageSize: 10000
    
  openmatch_config.yaml: |-
    ignoreLists:
      deindexed:
        duration: 800
        offset: 0
      expired:
        duration: 0
        offset: 800
      proposed:
        duration: 800
        offset: 0
    jsonkeys:
      mmfImage: imagename
      mmfService: hostname
      pools: properties.pools
      rosters: properties.rosters
    metrics:
      reportingPeriod: 5
    playerIndices:
    - char.cleric
    - char.knight
    - char.paladin
    - map.aleroth
    - map.oasis
    - mmr.rating
    - mode.battleroyale
    - mode.ctf
    - mode.demo
    - region.europe-east1
    - region.europe-west1
    - region.europe-west2
    - region.europe-west3
    - region.europe-west4
    - role.dps
    - role.support
    - role.tank
    redis:
      expirations:
        matchobject: 43200
        player: 43200
    
---
# Source: open-match/templates/mmforc-service-account.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mmforc-job-runner
  namespace: open-match
  labels:
    app: open-match
    chart: open-match-0.4.0
    release: open-match
    heritage: Tiller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mmforc-job-runner
subjects:
- kind: ServiceAccount
  name: mmforc-job-runner
  namespace: open-match
roleRef:
  kind: Role
  name: mmforc-job-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mmforc-job-runner
  namespace: open-match
  labels:
    app: open-match
    chart: open-match-0.4.0
    release: open-match
    heritage: Tiller
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]

---
# Source: open-match/templates/backendapi.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: Service
apiVersion: v1
metadata:
  name: om-backendapi
  namespace: open-match
  labels:
    app: open-match
spec:
  selector:
    app: open-match
    component: backend
  ports:
  - name: grpc
    protocol: TCP
    port: 50505
    targetPort: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-backendapi
  namespace: open-match
  labels:
    app: open-match
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match
      component: backend
  template:
    metadata:
      namespace: open-match
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9555"
        prometheus.io/path: /metrics
      labels:
        app: open-match
        component: backend
    spec:
      containers:
      - name: om-backend
        image: "ihrankouski/openmatch-backendapi:dev"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          subPath: openmatch_config.yaml
          mountPath: /config/openmatch_config.yaml
        - name: om-config-volume
          subPath: backendapi_config.yaml
          mountPath: /config/component_config.yaml
        ports:
        - name: grpc
          containerPort: 50505
        - name: metrics
          containerPort: 9555
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

---
# Source: open-match/templates/frontendapi.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: Service
apiVersion: v1
metadata:
  name: om-frontendapi
  namespace: open-match
  labels:
    app: open-match
spec:
  selector:
    app: open-match
    component: frontend
  ports:
  - name: grpc
    protocol: TCP
    port: 50504
    targetPort: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-frontendapi
  namespace: open-match
  labels:
    app: open-match
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match
      component: frontend
  template:
    metadata:
      namespace: open-match
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9555"
        prometheus.io/path: /metrics
      labels:
        app: open-match
        component: frontend
    spec:
      containers:
      - name: om-frontendapi
        image: "ihrankouski/openmatch-frontendapi:dev"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          subPath: openmatch_config.yaml
          mountPath: /config/openmatch_config.yaml
        - name: om-config-volume
          subPath: frontendapi_config.yaml
          mountPath: /config/component_config.yaml
        ports:
        - name: grpc
          containerPort: 50504
        - name: metrics
          containerPort: 9555
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

---
# Source: open-match/templates/mmlogicapi.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: Service
apiVersion: v1
metadata:
  name: om-mmlogicapi
  namespace: open-match
  labels:
    app: open-match
spec:
  selector:
    app: open-match
    component: mmlogic
  ports:
  - protocol: TCP
    port: 50503
    targetPort: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-mmlogicapi
  namespace: open-match
  labels:
    app: open-match
    component: mmlogic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match
      component: mmlogic
  template:
    metadata:
      namespace: open-match
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9555"
        prometheus.io/path: /metrics
      labels:
        app: open-match
        component: mmlogic
    spec:
      containers:
      - name: om-mmlogic
        image: "ihrankouski/openmatch-mmlogicapi:dev"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          subPath: openmatch_config.yaml
          mountPath: /config/openmatch_config.yaml
        - name: om-config-volume
          subPath: mmlogicapi_config.yaml
          mountPath: /config/component_config.yaml
        ports:
        - name: grpc
          containerPort: 50503
        - name: metrics
          containerPort: 9555
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

---
# Source: open-match/templates/mmforc.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-mmforc
  namespace: open-match
  labels:
    app: open-match
    component: mmforc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match
      component: mmforc
  template:
    metadata:
      namespace: open-match
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9555"
        prometheus.io/path: /metrics
      labels:
        app: open-match
        component: mmforc
    spec:
      serviceAccountName: mmforc-job-runner
      containers:
      - name: om-mmforc
        image: "ihrankouski/openmatch-mmforc:dev"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          subPath: openmatch_config.yaml
          mountPath: /config/openmatch_config.yaml
        - name: om-config-volume
          subPath: mmforc_config.yaml
          mountPath: /config/component_config.yaml
        ports:
        - name: metrics
          containerPort: 9555
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

---
# Source: open-match/templates/grafana-dashboards.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

