---
# Source: open-match-example/templates/testprofile-configmap.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
namespace: open-match
metadata:
  name: om-testprofile-config
  labels:
    app: open-match-example
    component: config
    chart: open-match-example-0.4.0
    release: open-match-example
    heritage: Tiller
data:
  testprofile.json: |
    {
      "imagename":"gcr.io/open-match-public-images/openmatch-mmf-py3-mmlogic-simple:latest",
      "name":"testprofilev1",
      "id":"testprofile",
      "properties":{
         "pools": [
            {
              "name": "defaultPool",
              "filters": [
                { "name": "europeWest1ElapsedUnder150", "attribute": "region.europe-west1", "maxv": "150" },
                { "name": "silverRanking", "attribute": "mmr.rating", "maxv": "1250", "minv": "950" }
              ]
            },
            {
              "name": "supportPool",
              "filters": [
                { "name": "europeWest1ElapsedUnder150", "attribute": "region.europe-west1", "maxv": "150" },
                { "name": "silverRanking", "attribute": "mmr.rating", "maxv": "1250", "minv": "950" },
                { "name": "supportRole", "attribute": "role.support", "maxv": "2147483647" }
              ]
            }
         ],
         "rosters": [
            {
              "name": "red",
              "players": [
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" }
              ]
            },
            {
              "name": "blu",
              "players": [
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" },
                { "pool": "defaultPool" }
              ]
            }
         ]
       }
    }
  

---
# Source: open-match-example/templates/backendclient.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-backendclient
  namespace: open-match
  labels:
    app: open-match-example
    component: backendclient
    chart: open-match-example-0.4.0
    release: open-match-example
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match-example
      component: backendclient
      chart: open-match-example-0.4.0
      release: open-match-example
      heritage: Tiller
  template:
    namespace: open-match
    metadata:
      labels:
        app: open-match-example
        component: backendclient
        chart: open-match-example-0.4.0
        release: open-match-example
        heritage: Tiller
    spec:
      containers:
      - name: om-backendclient
        image: "gcr.io/open-match-public-images/openmatch-backendclient:0.4.0"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          mountPath: /config
        - name: om-testprofile-volume
          mountPath: /profiles
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap
      - name: om-testprofile-volume
        configMap:
          name: om-testprofile-config

---
# Source: open-match-example/templates/clientloadgen.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-clientloadgen
  namespace: open-match
  labels:
    app: open-match-example
    component: clientloadgen
    chart: open-match-example-0.4.0
    release: open-match-example
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match-example
      component: clientloadgen
      chart: open-match-example-0.4.0
      release: open-match-example
      heritage: Tiller
  template:
    namespace: open-match
    metadata:
      labels:
        app: open-match-example
        component: clientloadgen
        chart: open-match-example-0.4.0
        release: open-match-example
        heritage: Tiller
    spec:
      containers:
      - name: om-clientloadgen
        image: "gcr.io/open-match-public-images/openmatch-clientloadgen:0.4.0"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          mountPath: /config
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

---
# Source: open-match-example/templates/evaluator.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-evaluator
  namespace: open-match
  labels:
    app: open-match-example
    component: evaluator
    chart: open-match-example-0.4.0
    release: open-match-example
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match-example
      component: evaluator
      chart: open-match-example-0.4.0
      release: open-match-example
      heritage: Tiller
  template:
    namespace: open-match
    metadata:
      labels:
        app: open-match-example
        component: evaluator
        chart: open-match-example-0.4.0
        release: open-match-example
        heritage: Tiller
    spec:
      containers:
      - name: om-evaluator
        image: "gcr.io/open-match-public-images/openmatch-evaluator-simple:0.4.0"
        imagePullPolicy: 
        volumeMounts:
        - name: om-config-volume
          mountPath: /config
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

---
# Source: open-match-example/templates/frontendclient.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-frontendclient
  namespace: open-match
  labels:
    app: open-match-example
    component: frontendclient
    chart: open-match-example-0.4.0
    release: open-match-example
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match-example
      component: frontendclient
      chart: open-match-example-0.4.0
      release: open-match-example
      heritage: Tiller
  template:
    namespace: open-match
    metadata:
      labels:
        app: open-match-example
        component: frontendclient
        chart: open-match-example-0.4.0
        release: open-match-example
        heritage: Tiller
    spec:
      containers:
      - name: om-frontendclient
        image: "gcr.io/open-match-public-images/openmatch-frontendclient:0.4.0"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          mountPath: /config
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

---
# Source: open-match-example/templates/function.yaml
# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-function
  namespace: open-match
  labels:
    app: open-match-example
    component: function
    chart: open-match-example-0.4.0
    release: open-match-example
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match-example
      component: function
      chart: open-match-example-0.4.0
      release: open-match-example
      heritage: Tiller
  template:
    namespace: open-match
    metadata:
      labels:
        app: open-match-example
        component: function
        chart: open-match-example-0.4.0
        release: open-match-example
        heritage: Tiller
    spec:
      containers:
      - name: om-function
        image: "gcr.io/open-match-public-images/openmatch-mmf-go-mmlogic-simple:0.4.0"
        imagePullPolicy: Always
        volumeMounts:
        - name: om-config-volume
          mountPath: /config
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap

