apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openmatch-metrics
  labels:
    app: openmatch
    agent: opencensus
    destination: prometheus
spec:
  selector:
    matchLabels:
      app: openmatch
      agent: opencensus
      destination: prometheus
  endpoints:
  - port: metrics
    interval: 10s
