apiVersion: v1
kind: Pod
metadata:
  name: om-director
  namespace: open-match
spec:
  containers:
  - name: om-director
    image: "some public images"
    imagePullPolicy: Always
  hostname: om-director
