# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file contains the sample minimal pod definitions for all of the components that one may need to use Open Match as a match maker.
# You can find the same pod definitions within the sub-folders under the /tutorials/ directory
# Run `kubectl apply -f matchmaker.yaml` to deploy these definitions.

apiVersion: v1
kind: Pod
metadata:
  name: default-eval-mmr-director
  namespace: default-eval-mmr
spec:
  containers:
  - name: default-eval-mmr-director
    image: REGISTRY_PLACEHOLDER/default-eval-mmr-director:latest
    imagePullPolicy: Always
  hostname: default-eval-mmr-director
---
apiVersion: v1
kind: Pod
metadata:
  name: default-eval-mmr-frontend
  namespace: default-eval-mmr
spec:
  containers:
  - name: default-eval-mmr-frontend
    image: REGISTRY_PLACEHOLDER/default-eval-mmr-frontend:latest
    imagePullPolicy: Always
  hostname: default-eval-mmr-frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: default-eval-mmr-matchfunction
  namespace: default-eval-mmr
  labels:
    app: default-eval-mmr
    component: matchfunction
spec:
  containers:
  - name: default-eval-mmr-matchfunction
    image: REGISTRY_PLACEHOLDER/default-eval-mmr-matchfunction:latest
    imagePullPolicy: Always
    ports:
    - name: grpc
      containerPort: 50502
---
kind: Service
apiVersion: v1
metadata:
  name: default-eval-mmr-matchfunction
  namespace: default-eval-mmr
  labels:
    app: default-eval-mmr
    component: matchfunction
spec:
  selector:
    app: default-eval-mmr
    component: matchfunction
  clusterIP: None
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 50502
---
