steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/openmatch-base:dev' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build', 
            '--tag=gcr.io/$PROJECT_ID/openmatch-backendapi:dev',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/openmatch-backendapi:dev']
